version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5525:5525"
    volumes:
      - /:/mnt/nas
      - ./config:/app/config
      - ./logs:/app/logs
      - ./static:/app/static
    environment:
      - NAS_MOUNT_POINT=/mnt/nas
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped

# 服务默认使用5525端口(Flask)
# 访问地址：http://主机IP:5525