auto_settings:
  alist_password: ''
  alist_username: ''
  enabled: true
  generate_interval: 0
  interval: 3600
  mount_mode: alist
  mount_root: ''
  output_path: ''
  recursive: true
  server: http://172.16.2.182:5244
  source_path: ''
  url_prefix: /dav
default_paths:
  output: /mnt/nas
  source: /mnt/nas
libraries: []
logging:
  backup_count: 5
  file: logs/strm.log
  level: INFO
  max_size: 10
manual_settings:
  alist_password: ''
  alist_username: ''
  interval: 0
  mount_mode: alist
  mount_root: ''
  recursive: true
  source_path: ''
  target_path: ''
mount_root: /mnt/nas
version: 1.0.0
